### ISSUE TITLE
[feature request] Specify location of config file

### ISSUE THREAD

**Issue by openendings** [realyze/pr-train#5]
E.g. `git pr-train --config-file=~/.pr-train-CA-1337.yml`.

Use case: "I have multiple PR trains in flight, and want to manage them all without any `ln -s` shenanigans."

**Comment by realyze** [comment]
Hey Chris, you can have multliple trains in the `.pr-train.yml`

```yml
trains:
  train for feature 1:
    - tomas/feature-1/foo
    - tomas/feature-1/bar

  train for feature 2:
    - tomas/feature-2/foofoo
    - tomas/feature-2/barbar
```

Does that address your issue?
